// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Cama
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class CamaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Cama>
    {
        public CamaConfiguration()
            : this("dbo")
        {
        }

        public CamaConfiguration(string schema)
        {
            ToTable("Cama", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DsCama).HasColumnName(@"dsCama").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(30);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
