// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Cama
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class Cama
    {
        public int Id { get; set; } // id (Primary key)
        public string DsCama { get; set; } // dsCama (length: 30)

        // Reverse navigation

        /// <summary>
        /// Child QuartoCamas where [QuartoCama].[idCama] point to this entity (fk_QuartoCama_Cama_idCama)
        /// </summary>
        public System.Collections.Generic.ICollection<QuartoCama> QuartoCamas { get; set; } // QuartoCama.fk_QuartoCama_Cama_idCama

        public Cama()
        {
            QuartoCamas = new System.Collections.Generic.List<QuartoCama>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
