// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Empresa
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class Empresa
    {
        public int Id { get; set; } // id (Primary key)
        public string Nome { get; set; } // nome (length: 30)
        public string Cnpj { get; set; } // cnpj (length: 14)
        public string Uf { get; set; } // uf (length: 2)
        public string Cidade { get; set; } // cidade (length: 20)
        public string Prefixo { get; set; } // prefixo (length: 6)
        public string Logradouro { get; set; } // logradouro (length: 40)
        public string Bairro { get; set; } // bairro (length: 20)
        public int Numero { get; set; } // numero
        public string Cep { get; set; } // cep (length: 8)
        public string Fone { get; set; } // fone (length: 12)
        public string Email { get; set; } // email (length: 30)
        public string DsComplemento { get; set; } // dsComplemento (length: 120)

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Empresa pointed by [Hospede].[id] (fk_Hospede_Empresa_idEmpresa)
        /// </summary>
        public Hospede Hospede { get; set; } // Hospede.fk_Hospede_Empresa_idEmpresa

        public Empresa()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
