// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // HospedagemPagamento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class HospedagemPagamentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HospedagemPagamento>
    {
        public HospedagemPagamentoConfiguration()
            : this("dbo")
        {
        }

        public HospedagemPagamentoConfiguration(string schema)
        {
            ToTable("HospedagemPagamento", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdHospdagem).HasColumnName(@"idHospdagem").HasColumnType("int").IsRequired();
            Property(x => x.DtPagamento).HasColumnName(@"dtPagamento").HasColumnType("datetime").IsRequired();
            Property(x => x.QtdDiaria).HasColumnName(@"qtdDiaria").HasColumnType("int").IsRequired();
            Property(x => x.VlTotalDiaria).HasColumnName(@"vlTotalDiaria").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.IdTipoPagamento).HasColumnName(@"idTipoPagamento").HasColumnType("int").IsRequired();
            Property(x => x.ObsPagamento).HasColumnName(@"obsPagamento").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.VlTotalConsumo).HasColumnName(@"vlTotalConsumo").HasColumnType("money").IsOptional().HasPrecision(19,4);
            Property(x => x.DtInicioDiaria).HasColumnName(@"dtInicioDiaria").HasColumnType("datetime").IsRequired();
            Property(x => x.DtFimDiaria).HasColumnName(@"dtFimDiaria").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Hospedagem).WithMany(b => b.HospedagemPagamentoes).HasForeignKey(c => c.IdHospdagem).WillCascadeOnDelete(false); // fk_HospedagemPagamento_Hospedagem_idHospedagem
            HasRequired(a => a.TipoPagamento).WithMany(b => b.HospedagemPagamentoes).HasForeignKey(c => c.IdTipoPagamento).WillCascadeOnDelete(false); // fk_HospedagemPagamento_TipoPagamento_idTipoPagamento
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
