// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // HospedagemConsumo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class HospedagemConsumo
    {
        public int Id { get; set; } // id (Primary key)
        public int IdHospedagem { get; set; } // idHospedagem
        public int IdProduto { get; set; } // idProduto
        public int QtdProduto { get; set; } // qtdProduto
        public System.DateTime DtConsumo { get; set; } // dtConsumo
        public string ObsConsumo { get; set; } // obsConsumo (length: 140)
        public bool FlPagamento { get; set; } // flPagamento

        // Foreign keys

        /// <summary>
        /// Parent Hospedagem pointed by [HospedagemConsumo].([IdHospedagem]) (fk_HospedagemConsumo_Hosdagem_idHospdagem)
        /// </summary>
        public Hospedagem Hospedagem { get; set; } // fk_HospedagemConsumo_Hosdagem_idHospdagem

        public HospedagemConsumo()
        {
            FlPagamento = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
