// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Hospedagem
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class HospedagemConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Hospedagem>
    {
        public HospedagemConfiguration()
            : this("dbo")
        {
        }

        public HospedagemConfiguration(string schema)
        {
            ToTable("Hospedagem", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DtCheckIn).HasColumnName(@"dtCheckIn").HasColumnType("datetime").IsRequired();
            Property(x => x.DtCheckOut).HasColumnName(@"dtCheckOut").HasColumnType("datetime").IsRequired();
            Property(x => x.IdQuartoAtual).HasColumnName(@"idQuartoAtual").HasColumnType("int").IsRequired();
            Property(x => x.NumHospedes).HasColumnName(@"numHospedes").HasColumnType("int").IsRequired();
            Property(x => x.IdPreReserva).HasColumnName(@"idPreReserva").HasColumnType("int").IsOptional();
            Property(x => x.IdUserCheckIn).HasColumnName(@"idUserCheckIn").HasColumnType("nvarchar").IsOptional().HasMaxLength(120);
            Property(x => x.IdUserCheckOut).HasColumnName(@"idUserCheckOut").HasColumnType("nvarchar").IsOptional().HasMaxLength(120);
            Property(x => x.VlDiariaAtual).HasColumnName(@"vlDiariaAtual").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.VlFechamentoConta).HasColumnName(@"vlFechamentoConta").HasColumnType("money").IsOptional().HasPrecision(19,4);

            // Foreign keys
            HasOptional(a => a.Reserva).WithMany(b => b.Hospedagems).HasForeignKey(c => c.IdPreReserva).WillCascadeOnDelete(false); // fk_Hospedagem_PreReserva_idPreReserva
            HasRequired(a => a.Quarto).WithMany(b => b.Hospedagems).HasForeignKey(c => c.IdQuartoAtual).WillCascadeOnDelete(false); // fk_Hospedagem_Quarto_idQuarto
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
