// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Hospede
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class Hospede
    {
        public int Id { get; set; } // id (Primary key)
        public string Nome { get; set; } // nome (length: 120)
        public string Cpf { get; set; } // cpf (length: 11)
        public string Uf { get; set; } // uf (length: 2)
        public string Cidade { get; set; } // cidade (length: 20)
        public string Prefixo { get; set; } // prefixo (length: 6)
        public string Logradouro { get; set; } // logradouro (length: 40)
        public string Bairro { get; set; } // bairro (length: 20)
        public int Numero { get; set; } // numero
        public string Cep { get; set; } // cep (length: 8)
        public string Fone { get; set; } // fone (length: 12)
        public string Email { get; set; } // email (length: 30)
        public string DsComplemento { get; set; } // dsComplemento (length: 300)
        public System.DateTime? DtNascimento { get; set; } // dtNascimento
        public int? IdEmpresa { get; set; } // idEmpresa

        // Reverse navigation

        /// <summary>
        /// Child HospedagemHospedes where [HospedagemHospede].[idHospede] point to this entity (fk_HospedegemHospede_Hospede_idHospede)
        /// </summary>
        public System.Collections.Generic.ICollection<HospedagemHospede> HospedagemHospedes { get; set; } // HospedagemHospede.fk_HospedegemHospede_Hospede_idHospede

        // Foreign keys

        /// <summary>
        /// Parent Empresa pointed by [Hospede].([Id]) (fk_Hospede_Empresa_idEmpresa)
        /// </summary>
        public Empresa Empresa { get; set; } // fk_Hospede_Empresa_idEmpresa

        public Hospede()
        {
            HospedagemHospedes = new System.Collections.Generic.List<HospedagemHospede>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
