// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // HospedagemDiaria
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class HospedagemDiaria
    {
        public int Id { get; set; } // id (Primary key)
        public int IdHospedagem { get; set; } // idHospedagem
        public int IdQuarto { get; set; } // idQuarto
        public int NumHospedes { get; set; } // numHospedes
        public System.DateTime DtDiaria { get; set; } // dtDiaria
        public decimal VlDiaria { get; set; } // vlDiaria
        public bool FlPagamento { get; set; } // flPagamento

        // Foreign keys

        /// <summary>
        /// Parent Hospedagem pointed by [HospedagemDiaria].([IdHospedagem]) (fk_DiariaHospedagem_Hospedagem_idHospedagem)
        /// </summary>
        public Hospedagem Hospedagem { get; set; } // fk_DiariaHospedagem_Hospedagem_idHospedagem
        /// <summary>
        /// Parent Quarto pointed by [HospedagemDiaria].([IdQuarto]) (fk_DiariaHospedagem_Quarto_idQuarto)
        /// </summary>
        public Quarto Quarto { get; set; } // fk_DiariaHospedagem_Quarto_idQuarto

        public HospedagemDiaria()
        {
            FlPagamento = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
