// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Hospede
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class HospedeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Hospede>
    {
        public HospedeConfiguration()
            : this("dbo")
        {
        }

        public HospedeConfiguration(string schema)
        {
            ToTable("Hospede", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Nome).HasColumnName(@"nome").HasColumnType("nvarchar").IsRequired().HasMaxLength(120);
            Property(x => x.Cpf).HasColumnName(@"cpf").HasColumnType("nvarchar").IsRequired().HasMaxLength(11);
            Property(x => x.Uf).HasColumnName(@"uf").HasColumnType("nvarchar").IsRequired().HasMaxLength(2);
            Property(x => x.Cidade).HasColumnName(@"cidade").HasColumnType("nvarchar").IsRequired().HasMaxLength(20);
            Property(x => x.Prefixo).HasColumnName(@"prefixo").HasColumnType("nvarchar").IsRequired().HasMaxLength(6);
            Property(x => x.Logradouro).HasColumnName(@"logradouro").HasColumnType("nvarchar").IsRequired().HasMaxLength(40);
            Property(x => x.Bairro).HasColumnName(@"bairro").HasColumnType("nvarchar").IsRequired().HasMaxLength(20);
            Property(x => x.Numero).HasColumnName(@"numero").HasColumnType("int").IsRequired();
            Property(x => x.Cep).HasColumnName(@"cep").HasColumnType("nvarchar").IsRequired().HasMaxLength(8);
            Property(x => x.Fone).HasColumnName(@"fone").HasColumnType("nvarchar").IsRequired().HasMaxLength(12);
            Property(x => x.Email).HasColumnName(@"email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.DsComplemento).HasColumnName(@"dsComplemento").HasColumnType("nvarchar").IsOptional().HasMaxLength(300);
            Property(x => x.DtNascimento).HasColumnName(@"dtNascimento").HasColumnType("datetime").IsOptional();
            Property(x => x.IdEmpresa).HasColumnName(@"idEmpresa").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.Empresa).WithOptional(b => b.Hospede).WillCascadeOnDelete(false); // fk_Hospede_Empresa_idEmpresa
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
