// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // HospedagemConsumo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class HospedagemConsumoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<HospedagemConsumo>
    {
        public HospedagemConsumoConfiguration()
            : this("dbo")
        {
        }

        public HospedagemConsumoConfiguration(string schema)
        {
            ToTable("HospedagemConsumo", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdHospedagem).HasColumnName(@"idHospedagem").HasColumnType("int").IsRequired();
            Property(x => x.IdProduto).HasColumnName(@"idProduto").HasColumnType("int").IsRequired();
            Property(x => x.QtdProduto).HasColumnName(@"qtdProduto").HasColumnType("int").IsRequired();
            Property(x => x.DtConsumo).HasColumnName(@"dtConsumo").HasColumnType("datetime").IsRequired();
            Property(x => x.ObsConsumo).HasColumnName(@"obsConsumo").HasColumnType("nvarchar").IsOptional().HasMaxLength(140);
            Property(x => x.FlPagamento).HasColumnName(@"flPagamento").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Hospedagem).WithMany(b => b.HospedagemConsumoes).HasForeignKey(c => c.IdHospedagem).WillCascadeOnDelete(false); // fk_HospedagemConsumo_Hosdagem_idHospdagem
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
