// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    public interface IIlhaBela : System.IDisposable
    {
        System.Data.Entity.DbSet<CaixaMovimento> CaixaMovimentoes { get; set; } // CaixaMovimento
        System.Data.Entity.DbSet<Cama> Camas { get; set; } // Cama
        System.Data.Entity.DbSet<Empresa> Empresas { get; set; } // Empresa
        System.Data.Entity.DbSet<Hospedagem> Hospedagems { get; set; } // Hospedagem
        System.Data.Entity.DbSet<HospedagemConsumo> HospedagemConsumoes { get; set; } // HospedagemConsumo
        System.Data.Entity.DbSet<HospedagemDiaria> HospedagemDiarias { get; set; } // HospedagemDiaria
        System.Data.Entity.DbSet<HospedagemHospede> HospedagemHospedes { get; set; } // HospedagemHospede
        System.Data.Entity.DbSet<HospedagemPagamento> HospedagemPagamentoes { get; set; } // HospedagemPagamento
        System.Data.Entity.DbSet<Hospede> Hospedes { get; set; } // Hospede
        System.Data.Entity.DbSet<Produto> Produtoes { get; set; } // Produto
        System.Data.Entity.DbSet<ProdutoMovimento> ProdutoMovimentoes { get; set; } // ProdutoMovimento
        System.Data.Entity.DbSet<Quarto> Quartos { get; set; } // Quarto
        System.Data.Entity.DbSet<QuartoCama> QuartoCamas { get; set; } // QuartoCama
        System.Data.Entity.DbSet<Reserva> Reservas { get; set; } // Reserva
        System.Data.Entity.DbSet<ReservaAgendamento> ReservaAgendamentoes { get; set; } // ReservaAgendamento
        System.Data.Entity.DbSet<ReservaPagamento> ReservaPagamentoes { get; set; } // ReservaPagamento
        System.Data.Entity.DbSet<ReservaQuarto> ReservaQuartoes { get; set; } // ReservaQuarto
        System.Data.Entity.DbSet<TipoOperacao> TipoOperacaos { get; set; } // TipoOperacao
        System.Data.Entity.DbSet<TipoPagamento> TipoPagamentoes { get; set; } // TipoPagamento
        System.Data.Entity.DbSet<TipoQuarto> TipoQuartoes { get; set; } // TipoQuarto

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
