// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ProdutoMovimento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ProdutoMovimento
    {
        public int Id { get; set; } // id (Primary key)
        public int IdProduto { get; set; } // idProduto

        ///<summary>
        /// &apos;E&apos; = Entrada  &apos;A&apos; = Venda Avulsa  &apos;V&apos; = Venda Apartamento
        ///</summary>
        public string TpMovimento { get; set; } // tpMovimento (length: 1)
        public int QtdProduto { get; set; } // qtdProduto
        public System.DateTime DtMovimento { get; set; } // dtMovimento
        public decimal VlTotal { get; set; } // vlTotal

        // Reverse navigation

        /// <summary>
        /// Child CaixaMovimentoes where [CaixaMovimento].[idProdutoMovimento] point to this entity (fk_CaixaMovimento_ProdutoMovimento_idProdutoMovimento)
        /// </summary>
        public System.Collections.Generic.ICollection<CaixaMovimento> CaixaMovimentoes { get; set; } // CaixaMovimento.fk_CaixaMovimento_ProdutoMovimento_idProdutoMovimento

        // Foreign keys

        /// <summary>
        /// Parent Produto pointed by [ProdutoMovimento].([IdProduto]) (fk_ProdutoMovimento_Produto_idProduto)
        /// </summary>
        public Produto Produto { get; set; } // fk_ProdutoMovimento_Produto_idProduto

        public ProdutoMovimento()
        {
            CaixaMovimentoes = new System.Collections.Generic.List<CaixaMovimento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
