// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ProdutoMovimento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ProdutoMovimentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ProdutoMovimento>
    {
        public ProdutoMovimentoConfiguration()
            : this("dbo")
        {
        }

        public ProdutoMovimentoConfiguration(string schema)
        {
            ToTable("ProdutoMovimento", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdProduto).HasColumnName(@"idProduto").HasColumnType("int").IsRequired();
            Property(x => x.TpMovimento).HasColumnName(@"tpMovimento").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1);
            Property(x => x.QtdProduto).HasColumnName(@"qtdProduto").HasColumnType("int").IsRequired();
            Property(x => x.DtMovimento).HasColumnName(@"dtMovimento").HasColumnType("datetime").IsRequired();
            Property(x => x.VlTotal).HasColumnName(@"vlTotal").HasColumnType("money").IsRequired().HasPrecision(19,4);

            // Foreign keys
            HasRequired(a => a.Produto).WithMany(b => b.ProdutoMovimentoes).HasForeignKey(c => c.IdProduto).WillCascadeOnDelete(false); // fk_ProdutoMovimento_Produto_idProduto
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
