// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // QuartoCama
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class QuartoCamaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QuartoCama>
    {
        public QuartoCamaConfiguration()
            : this("dbo")
        {
        }

        public QuartoCamaConfiguration(string schema)
        {
            ToTable("QuartoCama", schema);
            HasKey(x => new { x.IdQuarto, x.IdCama });

            Property(x => x.IdQuarto).HasColumnName(@"idQuarto").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdCama).HasColumnName(@"idCama").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.QtdCama).HasColumnName(@"qtdCama").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Cama).WithMany(b => b.QuartoCamas).HasForeignKey(c => c.IdCama).WillCascadeOnDelete(false); // fk_QuartoCama_Cama_idCama
            HasRequired(a => a.Quarto).WithMany(b => b.QuartoCamas).HasForeignKey(c => c.IdQuarto).WillCascadeOnDelete(false); // fk_QuartoCama_Quarto_idQuarto
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
