// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // QuartoCama
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class QuartoCama
    {
        public int IdQuarto { get; set; } // idQuarto (Primary key)
        public int IdCama { get; set; } // idCama (Primary key)
        public int QtdCama { get; set; } // qtdCama

        // Foreign keys

        /// <summary>
        /// Parent Cama pointed by [QuartoCama].([IdCama]) (fk_QuartoCama_Cama_idCama)
        /// </summary>
        public Cama Cama { get; set; } // fk_QuartoCama_Cama_idCama
        /// <summary>
        /// Parent Quarto pointed by [QuartoCama].([IdQuarto]) (fk_QuartoCama_Quarto_idQuarto)
        /// </summary>
        public Quarto Quarto { get; set; } // fk_QuartoCama_Quarto_idQuarto

        public QuartoCama()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
