// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Quarto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class Quarto
    {
        public int Id { get; set; } // id (Primary key)
        public int NumAp { get; set; } // numAp
        public int NumAndar { get; set; } // numAndar
        public int IdTipoQuarto { get; set; } // idTipoQuarto
        public string DsAp { get; set; } // dsAp
        public int FlSituacao { get; set; } // flSituacao
        public int? IdHospedagem { get; set; } // idHospedagem

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Quarto pointed by [ReservaQuarto].[id] (fk_PreReservaQuarto_Quarto_idQuarto)
        /// </summary>
        public ReservaQuarto ReservaQuarto { get; set; } // ReservaQuarto.fk_PreReservaQuarto_Quarto_idQuarto
        /// <summary>
        /// Child Hospedagems where [Hospedagem].[idQuartoAtual] point to this entity (fk_Hospedagem_Quarto_idQuarto)
        /// </summary>
        public System.Collections.Generic.ICollection<Hospedagem> Hospedagems { get; set; } // Hospedagem.fk_Hospedagem_Quarto_idQuarto
        /// <summary>
        /// Child HospedagemDiarias where [HospedagemDiaria].[idQuarto] point to this entity (fk_DiariaHospedagem_Quarto_idQuarto)
        /// </summary>
        public System.Collections.Generic.ICollection<HospedagemDiaria> HospedagemDiarias { get; set; } // HospedagemDiaria.fk_DiariaHospedagem_Quarto_idQuarto
        /// <summary>
        /// Child QuartoCamas where [QuartoCama].[idQuarto] point to this entity (fk_QuartoCama_Quarto_idQuarto)
        /// </summary>
        public System.Collections.Generic.ICollection<QuartoCama> QuartoCamas { get; set; } // QuartoCama.fk_QuartoCama_Quarto_idQuarto
        /// <summary>
        /// Child ReservaAgendamentoes where [ReservaAgendamento].[idQuarto] point to this entity (fk_Alocacao_Quarto_idQuarto)
        /// </summary>
        public System.Collections.Generic.ICollection<ReservaAgendamento> ReservaAgendamentoes { get; set; } // ReservaAgendamento.fk_Alocacao_Quarto_idQuarto

        // Foreign keys

        /// <summary>
        /// Parent TipoQuarto pointed by [Quarto].([IdTipoQuarto]) (fk_Quarto_TipoQuarto_idTipoQuarto)
        /// </summary>
        public TipoQuarto TipoQuarto { get; set; } // fk_Quarto_TipoQuarto_idTipoQuarto

        public Quarto()
        {
            Hospedagems = new System.Collections.Generic.List<Hospedagem>();
            HospedagemDiarias = new System.Collections.Generic.List<HospedagemDiaria>();
            QuartoCamas = new System.Collections.Generic.List<QuartoCama>();
            ReservaAgendamentoes = new System.Collections.Generic.List<ReservaAgendamento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
