// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Quarto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class QuartoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Quarto>
    {
        public QuartoConfiguration()
            : this("dbo")
        {
        }

        public QuartoConfiguration(string schema)
        {
            ToTable("Quarto", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NumAp).HasColumnName(@"numAp").HasColumnType("int").IsRequired();
            Property(x => x.NumAndar).HasColumnName(@"numAndar").HasColumnType("int").IsRequired();
            Property(x => x.IdTipoQuarto).HasColumnName(@"idTipoQuarto").HasColumnType("int").IsRequired();
            Property(x => x.DsAp).HasColumnName(@"dsAp").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.FlSituacao).HasColumnName(@"flSituacao").HasColumnType("int").IsRequired();
            Property(x => x.IdHospedagem).HasColumnName(@"idHospedagem").HasColumnType("int").IsOptional();

            // Foreign keys
            HasRequired(a => a.TipoQuarto).WithMany(b => b.Quartos).HasForeignKey(c => c.IdTipoQuarto).WillCascadeOnDelete(false); // fk_Quarto_TipoQuarto_idTipoQuarto
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
