// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ReservaAgendamento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ReservaAgendamentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ReservaAgendamento>
    {
        public ReservaAgendamentoConfiguration()
            : this("dbo")
        {
        }

        public ReservaAgendamentoConfiguration(string schema)
        {
            ToTable("ReservaAgendamento", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdReservaQuarto).HasColumnName(@"idReservaQuarto").HasColumnType("int").IsOptional();
            Property(x => x.IdQuarto).HasColumnName(@"idQuarto").HasColumnType("int").IsRequired();
            Property(x => x.IdHospdagem).HasColumnName(@"idHospdagem").HasColumnType("int").IsOptional();
            Property(x => x.DtCheckIn).HasColumnName(@"dtCheckIn").HasColumnType("datetime").IsRequired();
            Property(x => x.DtCheckOut).HasColumnName(@"dtCheckOut").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasOptional(a => a.ReservaQuarto).WithMany(b => b.ReservaAgendamentoes).HasForeignKey(c => c.IdReservaQuarto).WillCascadeOnDelete(false); // fk_Alocacao_PreReservaQuarto_idPreReservaQuarto
            HasRequired(a => a.Quarto).WithMany(b => b.ReservaAgendamentoes).HasForeignKey(c => c.IdQuarto).WillCascadeOnDelete(false); // fk_Alocacao_Quarto_idQuarto
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
