// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ReservaPagamento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ReservaPagamento
    {
        public int Id { get; set; } // id (Primary key)
        public int IdReserva { get; set; } // idReserva
        public System.DateTime DtPagamento { get; set; } // dtPagamento
        public decimal VlPago { get; set; } // vlPago
        public string ObsPagamento { get; set; } // obsPagamento (length: 1)

        // Foreign keys

        /// <summary>
        /// Parent Reserva pointed by [ReservaPagamento].([IdReserva]) (fl_ReservaPagamento_Reserva_idReserva)
        /// </summary>
        public Reserva Reserva { get; set; } // fl_ReservaPagamento_Reserva_idReserva

        public ReservaPagamento()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
