// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // Reserva
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ReservaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Reserva>
    {
        public ReservaConfiguration()
            : this("dbo")
        {
        }

        public ReservaConfiguration(string schema)
        {
            ToTable("Reserva", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NmReserva).HasColumnName(@"nmReserva").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(120);
            Property(x => x.DtCheckIn).HasColumnName(@"dtCheckIn").HasColumnType("datetime").IsRequired();
            Property(x => x.DtCheckOut).HasColumnName(@"dtCheckOut").HasColumnType("datetime").IsRequired();
            Property(x => x.IdTipoReserva).HasColumnName(@"idTipoReserva").HasColumnType("int").IsRequired();
            Property(x => x.Email).HasColumnName(@"email").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.DsCelular).HasColumnName(@"dsCelular").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(11);
            Property(x => x.FlZap).HasColumnName(@"flZap").HasColumnType("bit").IsOptional();
            Property(x => x.DsObsGeral).HasColumnName(@"dsObsGeral").HasColumnType("nvarchar(max)").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
