// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ReservaPagamento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ReservaPagamentoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ReservaPagamento>
    {
        public ReservaPagamentoConfiguration()
            : this("dbo")
        {
        }

        public ReservaPagamentoConfiguration(string schema)
        {
            ToTable("ReservaPagamento", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdReserva).HasColumnName(@"idReserva").HasColumnType("int").IsRequired();
            Property(x => x.DtPagamento).HasColumnName(@"dtPagamento").HasColumnType("datetime").IsRequired();
            Property(x => x.VlPago).HasColumnName(@"vlPago").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.ObsPagamento).HasColumnName(@"obsPagamento").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(1);

            // Foreign keys
            HasRequired(a => a.Reserva).WithMany(b => b.ReservaPagamentoes).HasForeignKey(c => c.IdReserva).WillCascadeOnDelete(false); // fl_ReservaPagamento_Reserva_idReserva
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
