// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ReservaAgendamento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ReservaAgendamento
    {
        public int Id { get; set; } // id (Primary key)
        public int? IdReservaQuarto { get; set; } // idReservaQuarto
        public int IdQuarto { get; set; } // idQuarto
        public int? IdHospdagem { get; set; } // idHospdagem
        public System.DateTime DtCheckIn { get; set; } // dtCheckIn
        public System.DateTime? DtCheckOut { get; set; } // dtCheckOut

        // Foreign keys

        /// <summary>
        /// Parent Quarto pointed by [ReservaAgendamento].([IdQuarto]) (fk_Alocacao_Quarto_idQuarto)
        /// </summary>
        public Quarto Quarto { get; set; } // fk_Alocacao_Quarto_idQuarto
        /// <summary>
        /// Parent ReservaQuarto pointed by [ReservaAgendamento].([IdReservaQuarto]) (fk_Alocacao_PreReservaQuarto_idPreReservaQuarto)
        /// </summary>
        public ReservaQuarto ReservaQuarto { get; set; } // fk_Alocacao_PreReservaQuarto_idPreReservaQuarto

        public ReservaAgendamento()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
