// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // ReservaQuarto
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class ReservaQuartoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ReservaQuarto>
    {
        public ReservaQuartoConfiguration()
            : this("dbo")
        {
        }

        public ReservaQuartoConfiguration(string schema)
        {
            ToTable("ReservaQuarto", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.IdReserva).HasColumnName(@"idReserva").HasColumnType("int").IsRequired();
            Property(x => x.IdQuarto).HasColumnName(@"idQuarto").HasColumnType("int").IsRequired();
            Property(x => x.QtdPessoa).HasColumnName(@"qtdPessoa").HasColumnType("int").IsRequired();
            Property(x => x.Valor).HasColumnName(@"valor").HasColumnType("money").IsRequired().HasPrecision(19,4);

            // Foreign keys
            HasRequired(a => a.Quarto).WithOptional(b => b.ReservaQuarto).WillCascadeOnDelete(false); // fk_PreReservaQuarto_Quarto_idQuarto
            HasRequired(a => a.Reserva).WithMany(b => b.ReservaQuartoes).HasForeignKey(c => c.IdReserva).WillCascadeOnDelete(false); // fk_PreReservaQuarto_PreReserva_idReserva
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
