// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // TipoPagamento
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class TipoPagamento
    {
        public int Id { get; set; } // id (Primary key)
        public string NmTipoPagamento { get; set; } // nmTipoPagamento (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child HospedagemPagamentoes where [HospedagemPagamento].[idTipoPagamento] point to this entity (fk_HospedagemPagamento_TipoPagamento_idTipoPagamento)
        /// </summary>
        public System.Collections.Generic.ICollection<HospedagemPagamento> HospedagemPagamentoes { get; set; } // HospedagemPagamento.fk_HospedagemPagamento_TipoPagamento_idTipoPagamento

        public TipoPagamento()
        {
            HospedagemPagamentoes = new System.Collections.Generic.List<HospedagemPagamento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
