// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ClassLibrary1
{

    // TipoOperacao
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public partial class TipoOperacao
    {
        public int Id { get; set; } // id (Primary key)
        public string NmTipoOperacao { get; set; } // nmTipoOperacao (length: 20)
        public string DsOperacao { get; set; } // dsOperacao (length: 200)

        // Reverse navigation

        /// <summary>
        /// Child CaixaMovimentoes where [CaixaMovimento].[idTipoOperacao] point to this entity (fk_CaixaMovimento_TipoOperacao_idTipoOperacao)
        /// </summary>
        public System.Collections.Generic.ICollection<CaixaMovimento> CaixaMovimentoes { get; set; } // CaixaMovimento.fk_CaixaMovimento_TipoOperacao_idTipoOperacao

        public TipoOperacao()
        {
            CaixaMovimentoes = new System.Collections.Generic.List<CaixaMovimento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
